config/routes.rb
Batontouchme::Application.routes.draw do
  resources :testers, only: [:new, :create, :index]

  resources :batons, only: [:index, :create, :update, :destroy, :edit] do
    collection do
      get 'daniel'
      get 'casa'
      get 'hulk'
      get 'think'
    end

    member do
      get 'useredit'
    end
  end

  resources :keys  
  resources :sessions, only: [:new, :create, :destroy]

  match '/signin', to:'sessions#new'
  match '/signout', to:'sessions#destroy', via: :delete

  match '/home', to: 'main#home'
  match '/info', to: 'main#info'
  match '/runners', to: 'main#runners'
  match '/find', to: 'main#find'
  match '/authkeys', to: 'main#authkeys'

  match '/runners/daniel', to: 'main#daniel'
  match '/runners/casanova', to: 'main#casanova'
  match '/runners/hulk', to: 'main#hulk'
  match '/runners/thinkerbell', to: 'main#thinkerbell'

  match '/runners/daniel/regist1', to: 'main#regist1'
  match '/runners/casanova/regist2', to: 'main#regist2'
  match '/runners/hulk/regist3', to: 'main#regist3'
  match '/runners/thinkerbell/regist4', to: 'main#regist4'

  match '/runners/daniel/create1', to: 'main#create1', via: [:post]
  match '/runners/casanova/create2', to: 'main#create2', via: [:post]
  match '/runners/hulk/create3', to: 'main#create3', via: [:post]
  match '/runners/thinkerbell/create4', to: 'main#create4', via: [:post]

  match '/runners/regist', to: 'main#regist'
  match '/runners/create', to: 'main#create'

  root to: "main#home"

end

app/controllers/main_controller.rb
#encoding: UTF-8
class MainController < ApplicationController
  # before_filter :signed_in_authkey, only: [:find,:regist,:regist1,:regist2,
                                      # :regist3,:regist4,:create,:create1,
                                      # :create2,:create3,:create4]
  before_filter :signed_in_authkey, only: [:find,:regist,
                                      :create,:create1,
                                      :create2,:create3,:create4]
                                      # :daniel, :casanova, :hulk, :thinkerbell]
  # before_filter :baton_greater, only: [:regist,:regist1,:regist2,
  #                                     :regist3,:regist4]                                      
  
  def home
  end

  def info
  end

  def runners
  end

  def find
    @batons = current_authkey.batons
  end

  def authkeys
    # @genkeys = current_authkey.genkeys
  end

  def daniel
  end

  def casanova
  end

  def hulk
  end

  def thinkerbell
  end

  def regist1
    flash[:error] = "테스팅 기간이 끝났습니다!"
    redirect_to root_path
  end

  def regist2
    flash[:error] = "테스팅 기간이 끝났습니다!"
    redirect_to root_path
  end

  def regist3
    flash[:error] = "테스팅 기간이 끝났습니다!"
    redirect_to root_path
  end

  def regist4
    flash[:error] = "테스팅 기간이 끝났습니다!"
    redirect_to root_path
  end

  def regist
    flash[:error] = "테스팅 기간이 끝났습니다!"
    redirect_to root_path
  end

  def create
    @baton = current_authkey.batons.build(params[:baton])
    @baton.runner_id = 0
    @baton.anywork = 1

    if @baton.save
      flash[:notice] = "바톤을 등록했습니다! 바톤은 5개까지 등록할 수 있습니다^^"
      redirect_to find_path
    else
      flash[:error] = "바톤 등록에 실패했습니다!"
      render action: "regist"
    end
  end

  def create1
    @baton = current_authkey.batons.build(params[:baton])
    @baton.runner_id = 1
    if @baton.save
      flash[:notice] = "바톤을 등록했습니다! 바톤은 5개까지 등록할 수 있습니다^^"
      redirect_to find_path
    else
      flash[:error] = "바톤 등록에 실패했습니다!"
      render action: "regist1"
    end
  end

  def create2
    @baton = current_authkey.batons.build(params[:baton])
    @baton.runner_id = 2
    if @baton.save
      flash[:notice] = "바톤을 등록했습니다! 바톤은 5개까지 등록할 수 있습니다^^"
      redirect_to find_path
    else
      flash[:error] = "바톤 등록에 실패했습니다!"
      render action: "regist2"
    end
  end

  def create3
    @baton = current_authkey.batons.build(params[:baton])
    @baton.runner_id = 3
    if @baton.save
      flash[:notice] = "바톤을 등록했습니다! 바톤은 5개까지 등록할 수 있습니다^^"
      redirect_to find_path
    else
      flash[:error] = "바톤 등록에 실패했습니다!"
      render action: "regist3"
    end
  end

  def create4
    @baton = current_authkey.batons.build(params[:baton])
    @baton.runner_id = 4
    if @baton.save
      flash[:notice] = "바톤을 등록했습니다! 바톤은 5개까지 등록할 수 있습니다^^"
      redirect_to find_path
    else
      flash[:error] = "바톤 등록에 실패했습니다!"
      render action: "regist4"
    end
  end

  protected

  def baton
    @baton = Baton.new
  end

  def baton_greater
    if current_authkey.batons.size >= 5
      flash[:notice] = "바톤을 5개 이상 생성할 수 없습니다^^"
      redirect_to root_path
    end
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/authkeys.html.slim
.background
	br
	.container#con-resize
		br
		.con-back
			#authkey
				h3 아래는 인증을 위한 번호 0개입니다. 당신의 소중한 지인들에게 나눠주세요^^
				/ #{@genkeys.split(" ").size}
				br
				.key-back
					h3#genbor 0
					/ = @genkeys
				= image_tag "batontouch.me.png"
		br

app/views/main/casanova.html.slim
.background
	br
	.container#con-resize
		br
		.con-back
			#runnerinfo
				= image_tag "casa/casa_main.png"
				= link_to "바톤 전달하기", runners_casanova_regist2_path, class: 'pull-right btn btn-primary'
			br
			.tabbable
				ul.nav.nav-tabs
					li.active
					a href="#photo" data-toggle="tab" 설명
				.tab-content
					.tab-pane.active#photo
						h2 1.지금 요리하러 갑니다.
						.rimg= image_tag "casa/casa_1.png"
						p 맨날 스팸 구워먹기는 질리고, 그렇다고 또 라면 먹기는 싫은데, 다른걸 해먹기는 귀찮아
						p 냉장고를 열어보면 이것 조금, 저것 조금, 남아있고.. 으아아아아!!!!!!! 오늘은 뭐 먹지! (탕 탕 탕, 지글지글 오늘은 뭘 먹고 싶으세요?)
						p 고민 말고, 저를 부르세요. 집에 있는 재료를 최대한 활용해 최대한의 만족을 드립니다.. 전국 MT촌과 집에서 갈고 닦은 실력으로 당신에게 맛있는 한끼를 선물합니다.
						br
						br
						br
						
						h2 2.당신의 쇼핑파트너
						.rimg= image_tag "casa/casa_3.png"
						.rimg= image_tag "casa/casa_4.png"
						p 이 남자의 패션 독특하다
						p 이 남자의 패션 재치 있다.
						p 유행의 최첨단을 달리지 않아도 된다!
						p 소소한 듯 하지만 재미있는 자신에게 맞는 패션코드. 어렵지 않다. 이 남자와 함께 쇼핑하러 가보자.
						br
						br
						br
						h2 3.인간 심심이
						.rimg= image_tag "casa/casa_8.png"
						p 애니팡 점수 노가다에 당신, 더 이상 할 일이 없어서 지루해 하고 있다면, 나를 불러달라.
						p 서울 21년 토박이며 작년부터 준 대전 인이 된 지방공대생과 함께, 공대 유머를 배워보자. 
						br
						br
						br
					.tab-pane#review
						.hero-unit
							p Here Review
		br
	br

app/views/main/daniel.html.slim
.background
	br
	.container#con-resize
		br
		.con-back
			#runnerinfo
				= image_tag "daniel/main_page.png"
				= link_to "바톤 전달하기", runners_daniel_regist1_path, class: 'pull-right btn btn-primary'
			br
			.tabbable
				ul.nav.nav-tabs
					li.active
						a href="#photo" data-toggle="tab" 설명
				.tab-content
					.tab-pane.active#photo
						h2 1.스피치101
						.rimg= image_tag "daniel/daniel_1.png"
						p “지금 당신의 프레젠테이션이 2% 부족한 이유는? 바로 색깔이 없다는 것!”
						p 프레젠테이션도 여러종류가 있습니다. 단순 정보전달용PPT, 데모&쇼가 가미된PPT, 설득을 목적으로하는PPT, 영감, 감동을 목적으로하는PPT 등 목적에 맞게 스크립트를 작성하고 PPT를 구성하는게 중요합니다!
						p 딱딱한 프레젠테이션은 NEVER! 연극을 준비 할때 처럼, 모든 제스처, 동선, 멘트는 하나의 흐름이 되어야합니다. “PPT만 잡고 있는 대학생들아 모여라! 진짜 승부는 스토리에 있다! PPT는 네X버 카페에서 해결하고 스토리텔링을 해보자!”
						br
						br
						br
						h2 2.IT기획자 & 디자이너들이여 개발자와 소통하라! 
						.rimg= image_tag "daniel/daniel_2.png"
						.rimg= image_tag "daniel/2_2.png"
						p “개발은 몰라도 되지만 시스템적 이해는 필수”
						p 1)기발한 아이디어가 세상으로 나오기 위해 뚫어야할 벽을 뚫자! (Storyboard, Wireframe & mockup 제작, user scenario 구성)
						p 아이디어를 실현 시키기 위해서는 아주! 아주! 구체적으로 표현하는게 정말 중요합니다. 기획자라면 추상적인 아이디어를 도면에 나열할 수 있어야 겠죠? 이때 필요한 Wireframe, mockup제작, storyboard를 함께 만들어 봅시다!
						p 2)아이템을 현실화 시켜줄 개발자와 소통하기 위해 그들이 필요한 가장 기본적인 틀과 구성이란?  (간단한 프로그래밍 개념 + 웹 & 앱 구성 및 동작에 대한 내용 ) 
						p 개발과 시스템에 관련된 용어에대해서 어느정도 알고 있으면, 커뮤니케이션이 정말 쉬워질 수 있어요~ 차근차근 소화해봅시다!
						br
						br
						br
						h2 3.미국대학(원) 더하기 캘리포니아 이야기
						.rimg= image_tag "daniel/3_1.jpg"
						p 미국 내에서도, 서부 대학과 그 주위 이야기는 정말 흥미로운 토크 주제죠!
						p 학교내에서 벌어지는 헥카톤대회에서부터 대학가의 맛집들 이야기! 항상 가을 같은 선선한 날씨에 옆동내에는 번화가 샌프란시스코에서 쇼핑하는 것도 재밌겠죠? 
						p 좀 더 옆으로가면 스타트업의 본고장 실리콘밸리도 있지요~ 페이스북 간판도 과연  파란색일까요? 구글에서는 어떤 점심을 먹을것 같나요?
						p 미국 대학(원), 미국생활이 궁금하다면!
						br
						br
						br
						h2 4. 언제, 어디든 불러만줘, 널 찍기 위해 달려간다!
						.rimg= image_tag "daniel/4.png"
						p 오늘도 홀로 셀카를 찍으세요? 
						p 오늘도 단체사진에 못 끼고 찍는 역할을맡고 있나요? 
						p 다니엘이 화보 한 장 만들어 드리러 갑니다! 언제든 어디든 불러만 주세요!
						br
						br
						br
					.tab-pane#review
						.hero-unit
							p Here Review
		br
	br

app/views/main/find.html.slim
.background
	br
	.container#con-resize
		br
		.con-back
			- flash.each do |name, msg|
				div class="alert alert-#{name == :notice ? 'success' : 'error'}"
					a.close data-dismiss="alert" x
					= msg
			- unless @batons.empty?
				h3 내 바톤은 어디에?
				- @batons.each do |baton|
					.span6
						h3 바톤 이름 : #{baton.taskname}
						p 어디서 : #{baton.address}
						p 날짜 : #{baton.date}
						p 시간 : #{baton.time}
						p WishList : #{baton.wish}
						- if baton.status_id.eql?(0)
							p 상태 : 바톤 전달 완료!(등록대기!)
							= link_to "수정", useredit_baton_path(baton), :class => 'btn btn-info'
							br
							br
						- elsif baton.status_id.eql?(1)
							p 상태 : 진행중!
							= link_to "수정", useredit_baton_path(baton), :class => 'btn btn-info'
							br
							br
						- elsif baton.status_id.eql?(2)
							p 상태 : 터치 다운!(완료!)
							br
							br
					.span2
						- if baton.runner_id.eql?(1)
							h3 Runner
							= image_tag "dan_profile.png"
						- elsif baton.runner_id.eql?(2)
							h3 Runner
							= image_tag "casa_profile.png"
						- elsif baton.runner_id.eql?(3)
							h3 Runner
							= image_tag "hulk_profile.png"
						- elsif baton.runner_id.eql?(4)
							h3 Runner
							= image_tag "jen_profile.png"
						- else
						  h4 Runner
						  p 러너가 정해지지 않았습니다^^
			- else
				br
				br
				br
				h3#batoncenter 바톤을 아직 전달하지 않았어요!
				#choosebtn
					= link_to "Runner 고르기", runners_path ,class: 'btn btn-info btn-large'
					'
					= link_to "BatonTouch NOW!", runners_regist_path, class: 'btn btn-success btn-large'
				br
				br
				br
			br
	br

app/views/main/home.html.slim
- flash.each do |name, msg|
  div class="alert alert-#{name == :notice ? 'success' : 'error'}"
    a.close data-dismiss="alert" x
    = msg
#myCarousel.carousel.slide
	.carousel-inner
		.active.item
			= image_tag "slide1.png", size: "1940x688"
		.item
			= image_tag "slide2.png", size: "1940x688"
			.carousel-caption#carousel-form
		/ .item
		/ 	= image_tag "main3.jpg", size: "1940x688"
		/ 	.carousel-caption#carousel-form
		/ 		form.form-inline accept-charset="UTF-8"
		/ 			.input-appended align="center"
		/ 				= link_to "BatonTouch NOW!", runners_regist_path, class: 'btn btn-primary batonbtn'
	a.carousel-control.left href="#myCarousel" data-slide="prev" &lsaquo;
	a.carousel-control.right href="#myCarousel" data-slide="next" &rsaquo;
	/ form.form-inline#buttonposition accept-charset="UTF-8"
	/ 	.input-appended align="center"
	/ 		= link_to "BatonTouch NOW!", runners_regist_path, class: 'btn btn-primary batonbtn'

app/views/main/regist.html.slim
.container
  .con-back
    #runnerinfo
      = image_tag "slide1.png"
    br
    br
  - flash.each do |name, msg|
    div class="alert alert-#{name == :notice ? 'success' : 'error'}"
      a.close data-dismiss="alert" x
      = msg
  = simple_form_for @baton, url:{controller:"main", action: "create"},:html => { :class => "form-horizontal" } do |f|
    = f.input :taskname, label:"어떤 일을 시키실래요?", placeholder: "ex) 짐 옮겨 주세요!", input_html: {value: @taskname}
    = f.input :phone, label: "전화번호", placeholder: "ex) 010-5555-5555"
    = f.input :detail, label: "세부사항", placeholder: "ex) 부재중에는 경비실에 맡겨주세요! 안에 든 물건이 약하니 파손되지 않도록 신경써주세요!", hint: "일을 할때 필요한 모든 상세사항을 적어주세요!"
    = f.input :address, label: "주소", hint: "러너가 일을 수행할 주소를 구체적으로 끝까지 적어주세요!", placeholder: "ex)서울특별시 송파구 문정2동 훼미리 아파트 203동 1705호"
    = f.input :date, label: "날짜", placeholder: "시작 날짜를 선택하세요!", as: :string, input_html: {class: 'datepicker'},hint: "1차 이용가능 기간은 9월 24일부터 9월 28일까지입니다!"
    = f.input :time, label: "시간", placeholder: "일 시작 시간을 선택하세요!",as: :string, input_html: {class: 'timepicker'},hint: "신청 가능시간은 오전 10시(10:00AM)부터 오후 10시(10:00PM)까지입니다!"
    = f.input :wish, label: "Wish List", as: :select, collection:['라면 2번들','책1권','기타 조율 가능합니다^^']
    .form-actions#createbtn
      = link_to t('.cancel', :default => t("helpers.links.cancel")), runners_daniel_path, :class => 'btn'
      '
      = f.button :submit, :class => 'btn-primary'

app/views/main/regist1.html.slim
.container
  .con-back
    #runnerinfo
      = image_tag "daniel/main_page.png"
    br
    brtpa
  - flash.each do |name, msg|
    div class="alert alert-#{name == :notice ? 'success' : 'error'}"
      a.close data-dismiss="alert" x
      = msg
  = simple_form_for @baton,url:{controller:"main", action: "create1"}, :html => { :class => "form-horizontal" } do |f|
    = f.input :taskname, label:"어떤 일을 시키실래요?", placeholder: "ex) 세미나 준비를 도와주세요!"
    = f.input :phone, label: "전화번호", placeholder: "ex) 010-5555-5555"
    = f.input :detail, label: "세부사항", placeholder: "ex) 세미나 발표를 준비 중인데 스크립트를 아직 완성 못했어요. 좀 더 임팩트있게 구성하고 싶은데 도와주세요!", hint: "일을 할때 필요한 모든 상세사항을 적어주세요!"
    = f.input :address, label: "주소", hint: "러너가 일을 수행할 주소를 구체적으로 끝까지 적어주세요!", placeholder: "ex)서울특별시 송파구 문정2동 훼미리 아파트 203동 1705호"
    = f.input :date, label: "날짜", placeholder: "시작 날짜를 선택하세요!", as: :string, input_html: {class: 'datepicker'},hint: "1차 이용가능 기간은 9월 24일부터 9월 28일까지입니다!"
    = f.input :time, label: "시간", placeholder: "일 시작 시간을 선택하세요!",as: :string, input_html: {class: 'timepicker'},hint: "신청 가능시간은 오전 10시(10:00AM)부터 오후 10시(10:00PM)까지입니다!"
    = f.input :wish, label: "Wish List", as: :select, collection:['밥','아이스크림','커피 한잔','기타'], hint: "일을 끝낸 러너에게 줄 선물을 골라주세요!"
    .form-actions#createbtn
      = link_to t('.cancel', :default => t("helpers.links.cancel")), runners_daniel_path, :class => 'btn'
      '
      = f.button :submit, :class => 'btn-primary'
  

app/views/main/regist2.html.slim
.container
  .con-back
    #runnerinfo
      = image_tag "casa/casa_main.png"
    br
    br
  - flash.each do |name, msg|
    div class="alert alert-#{name == :notice ? 'success' : 'error'}"
      a.close data-dismiss="alert" x
      = msg
  = simple_form_for @baton,url:{controller:"main", action: "create2"}, :html => { :class => "form-horizontal" } do |f|
    = f.input :taskname, label:"어떤 일을 시키실래요?", placeholder: "ex) 아침을 준비해주세요!"
    = f.input :phone, label: "전화번호", placeholder: "ex) 010-5555-5555"
    = f.input :detail, label: "세부사항", placeholder: "ex) 항상 출근 준비에 바빠서 밥먹을 시간은 있는데 밥을 준비할 시간이 없어서 아침을 못챙겨먹고 있어요. 왠지 카사노바님의 맛있는 요리가 기대되네요! 아침 맛있게 해주세요!", hint: "일을 할때 필요한 모든 상세사항을 적어주세요!"
    = f.input :address, label: "주소", hint: "러너가 일을 수행할 주소를 구체적으로 끝까지 적어주세요!", placeholder: "ex)서울특별시 송파구 문정2동 훼미리 아파트 203동 1705호"
    = f.input :date, label: "날짜", placeholder: "시작 날짜를 선택하세요!", as: :string, input_html:{class: 'datepicker'},hint: "1차 이용가능 기간은 9월 24일부터 9월 28일까지입니다!"
    = f.input :time, label: "시간", placeholder: "일 시작 시간을 선택하세요!", input_html: {class: 'timepicker'},hint: "신청 가능시간은 오전 10시(10:00AM)부터 오후 10시(10:00PM)까지입니다!"
    = f.input :wish, label: "Wish List", as: :select, collection:['밥','아이스크림','커피 한잔','기타'], hint: "일을 끝낸 러너에게 줄 선물을 골라주세요!"
    .form-actions#createbtn
      = link_to t('.cancel', :default => t("helpers.links.cancel")), runners_daniel_path, :class => 'btn'
      '
      = f.button :submit, :class => 'btn-primary'

app/views/main/regist3.html.slim
.container
  .con-back
    #runnerinfo
      = image_tag "hulk/hulk_main.png"
    br
    br
  - flash.each do |name, msg|
    div class="alert alert-#{name == :notice ? 'success' : 'error'}"
      a.close data-dismiss="alert" x
      = msg
  = simple_form_for @baton,url:{controller:"main", action: "create3"}, :html => { :class => "form-horizontal" } do |f|
    = f.input :taskname, label:"어떤 일을 시키실래요?", placeholder: "ex) 컴퓨터 과제 좀 도와주세요!!"
    = f.input :phone, label: "전화번호", placeholder: "ex) 010-5555-5555"
    = f.input :detail, label: "세부사항", placeholder: "ex) 과제 받았는데 제가 어느정도는 풀었거든요. 근데 한 부분이 계속 막히네요. 좀 도와주세요!", hint: "일을 할때 필요한 모든 상세사항을 적어주세요!"
    = f.input :address, label: "주소", hint: "러너가 일을 수행할 주소를 구체적으로 끝까지 적어주세요!", placeholder: "ex)서울특별시 송파구 문정2동 훼미리 아파트 203동 1705호"
    = f.input :date, label: "날짜", placeholder: "시작 날짜를 선택하세요!", as: :string, input_html: {class: 'datepicker'},hint: "1차 이용가능 기간은 9월 24일부터 9월 28일까지입니다!"
    = f.input :time, label: "시간", placeholder: "일 시작 시간을 선택하세요!", input_html: {class: 'timepicker'},hint: "신청 가능시간은 오전 10시(10:00AM)부터 오후 10시(10:00PM)까지입니다!"
    = f.input :wish, label: "Wish List", as: :select, collection:['밥','아이스크림','커피 한잔','기타'], hint: "일을 끝낸 러너에게 줄 선물을 골라주세요!"
    .form-actions#createbtn
      = link_to t('.cancel', :default => t("helpers.links.cancel")), runners_daniel_path, :class => 'btn'
      '
      = f.button :submit, :class => 'btn-primary'

app/views/main/regist4.html.slim
.container
  .con-back
    #runnerinfo
      = image_tag "jen/main_page.png"
    br
    br
  - flash.each do |name, msg|
    div class="alert alert-#{name == :notice ? 'success' : 'error'}"
      a.close data-dismiss="alert" x
      = msg
  = simple_form_for @baton,url:{controller:"main", action: "create4"}, :html => { :class => "form-horizontal" } do |f|
    = f.input :taskname, label:"어떤 일을 시키실래요?", placeholder: "ex) 장 좀 봐주세요!"
    = f.input :phone, label: "전화번호", placeholder: "ex) 010-5555-5555"
    = f.input :detail, label: "세부사항", placeholder: "ex) 마트가서 신선한 과일이나 고기들을 골라주세요. 이번주가 여자친구 생일이거든요. 제가 직접 요리해줄려구요 :) 최고의 음식재료들을 사다주세요! 전 요리책을 보고 잇을게요.. ㅠ", hint: "일을 할때 필요한 모든 상세사항을 적어주세요!"
    = f.input :address, label: "주소", hint: "러너가 일을 수행할 주소를 구체적으로 끝까지 적어주세요!", placeholder: "ex)서울특별시 송파구 문정2동 훼미리 아파트 203동 1705호"
    = f.input :date, label: "날짜", placeholder: "시작 날짜를 선택하세요!", as: :string, input_html: {class: 'datepicker'},hint: "1차 이용가능 기간은 9월 24일부터 9월 28일까지입니다!"
    = f.input :time, label: "시간", placeholder: "일 시작 시간을 선택하세요!", input_html: {class: 'timepicker'},hint: "신청 가능시간은 오전 10시(10:00AM)부터 오후 10시(10:00PM)까지입니다!"
    = f.input :wish, label: "Wish List", as: :select, collection:['밥','아이스크림','커피 한잔','기타'], hint: "일을 끝낸 러너에게 줄 선물을 골라주세요!"
    .form-actions#createbtn
      = link_to t('.cancel', :default => t("helpers.links.cancel")), runners_daniel_path, :class => 'btn'
      '
      = f.button :submit, :class => 'btn-primary'

app/views/main/runners.html.slim
.container.con-resize
	br
	= image_tag "cancanbaton.png"
	br
	br
.runner-section
	.row-fluid
		.span3#runnerf
			/ .thumbnail
			= link_to runners_daniel_path do
				= image_tag "dan_profile.png", size: "320x480", class: "runimg"
				br
				button.btn.btn-primary.chbtn 다니엘에게 전달하기
		.span3#runner
			/ .thumbnail
			= link_to	runners_casanova_path do
				= image_tag "casa_profile.png",size:"320x480"
				br
				button.btn.btn-primary.chbtn 카사노바에게 전달하기
		.span3#runner
			/ .thumbnail
			= link_to runners_hulk_path do
				= image_tag "hulk_profile.png",size:"320x480"
				br
				button.btn.btn-primary.chbtn 건실청년에게 전달하기
		.span3#runner
			/ .thumbnail
			= link_to runners_thinkerbell_path do
				= image_tag "jen_profile.png",size:"320x480"
				br
				button.btn.btn-primary.chbtn 팅커벨에게 전달하기