config/routes.rb
Batontouchme::Application.routes.draw do
  resources :testers, only: [:new, :create, :index]

  resources :batons, only: [:index, :create, :update, :destroy, :edit] do
    collection do
      get 'daniel'
      get 'casa'
      get 'hulk'
      get 'think'
    end

    member do
      get 'useredit'
    end
  end

  resources :keys  
  resources :sessions, only: [:new, :create, :destroy]

  match '/signin', to:'sessions#new'
  match '/signout', to:'sessions#destroy', via: :delete

  match '/home', to: 'main#home'
  match '/info', to: 'main#info'
  match '/runners', to: 'main#runners'
  match '/find', to: 'main#find'
  match '/authkeys', to: 'main#authkeys'

  match '/runners/daniel', to: 'main#daniel'
  match '/runners/casanova', to: 'main#casanova'
  match '/runners/hulk', to: 'main#hulk'
  match '/runners/thinkerbell', to: 'main#thinkerbell'

  match '/runners/daniel/regist1', to: 'main#regist1'
  match '/runners/casanova/regist2', to: 'main#regist2'
  match '/runners/hulk/regist3', to: 'main#regist3'
  match '/runners/thinkerbell/regist4', to: 'main#regist4'

  match '/runners/daniel/create1', to: 'main#create1', via: [:post]
  match '/runners/casanova/create2', to: 'main#create2', via: [:post]
  match '/runners/hulk/create3', to: 'main#create3', via: [:post]
  match '/runners/thinkerbell/create4', to: 'main#create4', via: [:post]

  match '/runners/regist', to: 'main#regist'
  match '/runners/create', to: 'main#create'

  root to: "main#home"

end

app/models/tester.rb
#encoding: UTF-8
class Tester < ActiveRecord::Base
	attr_accessible :mail, :phone, :advtg


	valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :mail, presence: {message: "이메일은 필수입니다!"}, format: {with: valid_email_regex, message: "이메일 형식에 맞지 않아요!"},uniqueness: {case_sensitive: false, message: "이미 등록하신 이메일입니다!"}
end

app/controllers/testers_controller.rb
#encoding: UTF-8
class TestersController < ApplicationController
  before_filter :signed_in_authkey, only: [:index]
  # GET /testers
  # GET /testers.json
  def index
    if current_authkey.authkey.eql?("#fl0wk27er")
      @testers = Tester.all
    else
      redirect_to root_path
    end
  end

  # GET /testers/new
  # GET /testers/new.json
  def new
    @tester = Tester.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tester }
    end
  end

  # POST /testers
  # POST /testers.json
  def create
    @tester = Tester.new(params[:tester])

    if @tester.save
      flash[:notice] = "성공적으로 신청이 완료되었습니다^^"
      redirect_to root_path
    else
      flash[:error] = "러너 등록에 실패했습니다."
      render action: "new"
    end
  end
end

app/helpers/testers_helper.rb
module TestersHelper
end

app/views/testers/_form.html.slim
= simple_form_for(@tester) do |f|
  = f.error_notification

  .form-inputs
    = f.input :mail
    = f.input :phone
    = f.input :advtg

  .form-actions
    = f.button :submit

app/views/testers/edit.html.slim
h1 Editing tester

== render 'form'

= link_to 'Show', @tester
'|
= link_to 'Back', testers_path

app/views/testers/index.html.slim
h1 Listing testers

table
  tr
    th Mail
    th Phone
    th Advtg

  - @testers.each do |tester|

    tr
      td = tester.mail
      td = tester.phone
      td = tester.advtg

app/views/testers/new.html.slim
.container
  .con-back
    #runnerinfo
      = image_tag "slide1.png"
    br
    br
  - flash.each do |name, msg|
    div class="alert alert-#{name == :notice ? 'success' : 'error'}"
      a.close data-dismiss="alert" x
      = msg
  = simple_form_for @tester,:html => { :class => "form-horizontal" } do |f|
  	= f.input :mail, label: "E-mail", placeholder: "이메일은 필수입니다!"
  	= f.input :phone, label: "전화번호", placeholder: "전화번호를 정확히 입력하시면 우선순위로 연락을 드립니다! 필수는 아녜요^^"
  	= f.input :advtg, label: "어떤 일을 잘하시나요?", placeholder: "여러분이 러너가 된다면 어떤 일을 하고 싶으신가요? ex) 전공, 취미, 걍 힘쓰는 일, 같이 밥먹어주기, 놀아주기, 사진 찍어주기 등등 여러분이 할 수 있는 일을 적어주세요.", as: :text
  	= f.submit '신청하기', :class => 'btn btn-primary testsub'

app/views/testers/show.html.slim
p#notice = notice

p
  strong Mail:
  = @tester.mail
p
  strong Phone:
  = @tester.phone
p
  strong Advtg:
  = @tester.advtg

= link_to 'Edit', edit_tester_path(@tester)
'|
= link_to 'Back', testers_path