config/routes.rb
Batontouchme::Application.routes.draw do
  resources :testers, only: [:new, :create, :index]

  resources :batons, only: [:index, :create, :update, :destroy, :edit] do
    collection do
      get 'daniel'
      get 'casa'
      get 'hulk'
      get 'think'
    end

    member do
      get 'useredit'
    end
  end

  resources :keys  
  resources :sessions, only: [:new, :create, :destroy]

  match '/signin', to:'sessions#new'
  match '/signout', to:'sessions#destroy', via: :delete

  match '/home', to: 'main#home'
  match '/info', to: 'main#info'
  match '/runners', to: 'main#runners'
  match '/find', to: 'main#find'
  match '/authkeys', to: 'main#authkeys'

  match '/runners/daniel', to: 'main#daniel'
  match '/runners/casanova', to: 'main#casanova'
  match '/runners/hulk', to: 'main#hulk'
  match '/runners/thinkerbell', to: 'main#thinkerbell'

  match '/runners/daniel/regist1', to: 'main#regist1'
  match '/runners/casanova/regist2', to: 'main#regist2'
  match '/runners/hulk/regist3', to: 'main#regist3'
  match '/runners/thinkerbell/regist4', to: 'main#regist4'

  match '/runners/daniel/create1', to: 'main#create1', via: [:post]
  match '/runners/casanova/create2', to: 'main#create2', via: [:post]
  match '/runners/hulk/create3', to: 'main#create3', via: [:post]
  match '/runners/thinkerbell/create4', to: 'main#create4', via: [:post]

  match '/runners/regist', to: 'main#regist'
  match '/runners/create', to: 'main#create'

  root to: "main#home"

end

app/models/baton.rb
#encoding: UTF-8
class Baton < ActiveRecord::Base
	default_scope order: 'created_at DESC'
	scope :daniel, where(runner_id:1) 
	scope :casa, where(runner_id:2) 
	scope :hulk, where(runner_id:3) 
	scope :think, where(runner_id:4) 
	scope :anyone, where(runner_id:0)

	scope :ready, where(status_id:0)
	scope :progress, where(status_id:1)
	scope :done, where(status_id:2)

	attr_accessible :taskname, :phone, :detail, :address, :date, :time, :wish, :status_id, :runner_id

	validates :taskname, presence: { message: "어떤 일을 맡기실지 입력하셔야되요!" }
	validates :phone, format: {with:/\d{3}-\d{4,}-\d{4,}|\d{3}\d{4,}\d{4,}/, message: "전화번호 형식으로 등록해주세요!"}
	validates	:detail, presence: { message: "세부 사항을 꼭 적어주세요!" }
	validates	:address, presence: { message: "주소를 꼭 입력해주세요!" }
	validates	:date, presence: { message: "날짜가 꼭 필요합니다!" }
	validates	:wish, presence: { message: "WishList를 꼭 골라주세요!" }

	has_many :reviews
	belongs_to :authkey
end

app/controllers/batons_controller.rb
#encoding: UTF-8
class BatonsController < ApplicationController
  before_filter :signed_in_authkey, only: [:index, :edit,:useredit, :update, :daniel, :casa, :hulk, :think]
  # GET /batons
  # GET /batons.json
  def index
    if current_authkey.authkey.eql?("#fl0wk27er")
      @batons = Baton.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @batons }
      end
    elsif current_authkey.authkey.eql?("#daneld2130")
      redirect_to daniel_batons_path
    elsif current_authkey.authkey.eql?("#cassaj0105")
      redirect_to casa_batons_path
    elsif current_authkey.authkey.eql?("#hulkh2051")
      redirect_to hulk_batons_path
    elsif current_authkey.authkey.eql?("#genllt5055")
      redirect_to think_batons_path
    else
      redirect_to root_path
    end
  end

  def daniel
    if current_authkey.authkey.eql?("#daneld2130")
      @batons = Baton.daniel
      @anys = Baton.anyone
    else
      redirect_to root_path
    end
  end

  def casa
    if current_authkey.authkey.eql?("#cassaj0105")
      @batons = Baton.casa
      @anys = Baton.anyone
    else
      redirect_to root_path
    end
  end

  def hulk
    if current_authkey.authkey.eql?("#hulkh2051")
      @batons = Baton.hulk
      @anys = Baton.anyone
    else
      redirect_to root_path
    end
  end

  def think
    if current_authkey.authkey.eql?("#genllt5055")
      @batons = Baton.think
      @anys = Baton.anyone
    else
      redirect_to root_path
    end
  end

  # GET /batons/1
  # GET /batons/1.json
  def show
    @baton = Baton.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @baton }
    end
  end

  # GET /batons/new
  # GET /batons/new.json
  def new
    @baton = Baton.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @baton }
    end
  end

  # GET /batons/1/edit
  def edit
    @baton = Baton.find(params[:id])
  end

  def useredit
    @baton = Baton.find(params[:id])
  end

  # POST /batons
  # POST /batons.json
  def create
    @baton = Baton.new(params[:baton])

    respond_to do |format|
      if @baton.save
        format.html { redirect_to @baton, notice: 'Baton was successfully created.' }
        format.json { render json: @baton, status: :created, location: @baton }
      else
        format.html { render action: "new" }
        format.json { render json: @baton.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /batons/1
  # PUT /batons/1.json
  def update
    @baton = Baton.find(params[:id])

    if @baton.update_attributes(params[:baton])
      flash[:notice] = "성공적으로 바톤이 수정되었습니다!"
      redirect_to find_path
    else
      flash[:error] = "바톤 등록에 실패했습니다!"
      render action: "useredit"
    end

  end

  # DELETE /batons/1
  # DELETE /batons/1.json
  def destroy
    @baton = Baton.find(params[:id])
    @baton.destroy

    respond_to do |format|
      format.html { redirect_to batons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/batons_helper.rb
module BatonsHelper
end

app/views/batons/_form.html.slim
- if current_authkey.authkey.eql?("#fl0wk27er")
  = simple_form_for @baton, :html => { :class => "form-horizontal" } do |f|
    = f.input :taskname
    = f.input :phone
    = f.input :detail
    = f.input :address
    = f.input :date
    = f.input :time
    = f.input :status_id, collection: 0..2, as: :radio_buttons
    = f.input :wish
    = f.input :runner_id, collection: 0..4, as: :radio_buttons
    .form-actions
      = f.button :submit, :class => 'btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), batons_path, :class => 'btn'
- else
  = simple_form_for @baton, :html => { :class => "form-horizontal" } do |f|
    = f.input :taskname, disabled: true
    = f.input :phone, disabled: true
    = f.input :detail, disabled: true
    = f.input :address, disabled: true
    = f.input :date
    = f.input :time
    = f.input :status_id, collection: 0..2, as: :radio_buttons
    = f.input :wish
    - if @baton.runner_id.eql?(0)
      - if current_authkey.authkey.eql?("#daneld2130")
        = f.input :runner_id, collection: [0,1], as: :radio_buttons
      - elsif current_authkey.authkey.eql?("#cassaj0105")
        = f.input :runner_id, collection: [0,2], as: :radio_buttons
      - elsif current_authkey.authkey.eql?("#hulkh2051")
        = f.input :runner_id, collection: [0,3], as: :radio_buttons
      - elsif current_authkey.authkey.eql?("#genllt5055")
        = f.input :runner_id, collection: [0,4], as: :radio_buttons
      
    .form-actions
      = f.button :submit, :class => 'btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), batons_path, :class => 'btn'

app/views/batons/casa.html.slim
- model_class = Baton
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize
.tabbable
  ul.nav.nav-tabs
    li.active
      a href="#me" data-toggle="tab" Me
    li
      a href="#anyone" data-toggle="tab" Anyone
  .tab-content
    .tab-pane.active#me
      table class="table table-striped"
        thead
          tr
            th= model_class.human_attribute_name(:id)
            th= model_class.human_attribute_name(:taskname)
            th= model_class.human_attribute_name(:phone)
            th= model_class.human_attribute_name(:detail)
            th= model_class.human_attribute_name(:address)
            th= model_class.human_attribute_name(:date)
            th= model_class.human_attribute_name(:time)
            th= model_class.human_attribute_name(:runner_id)
            th= model_class.human_attribute_name(:status_id)
            th= model_class.human_attribute_name(:authkey_id)
            th= model_class.human_attribute_name(:wish)
            th= model_class.human_attribute_name(:created_at)
            th=t '.actions', :default => t("helpers.actions")
        tbody
          - @batons.each do |baton|
            tr
              td= link_to baton.id, baton_path(baton)
              td= baton.taskname
              td= baton.phone
              td= baton.detail
              td= baton.address
              td= baton.date
              td= baton.time
              td
                - if baton.runner_id.eql?(1)
                  | 다니엘
                - elsif baton.runner_id.eql?(2)
                  | 카사노바
                - elsif baton.runner_id.eql?(3)
                  | 헐크
                - elsif baton.runner_id.eql?(4)
                  | 팅커벨
                - else
                  | 아무나
              td
                - if baton.status_id.eql?(0)
                  | 등록대기상태
                - elsif baton.status_id.eql?(1)
                  | 진행중
                - elsif baton.status_id.eql?(2)
                  | 완료
              td= baton.authkey.authkey
              td= baton.wish
              td=l baton.created_at
              td
                = link_to t('.edit', :default => t("helpers.links.edit")), edit_baton_path(baton), :class => 'btn btn-mini'
    .tab-pane#anyone
      table class="table table-striped"
        thead
          tr
            th= model_class.human_attribute_name(:id)
            th= model_class.human_attribute_name(:taskname)
            th= model_class.human_attribute_name(:phone)
            th= model_class.human_attribute_name(:detail)
            th= model_class.human_attribute_name(:address)
            th= model_class.human_attribute_name(:date)
            th= model_class.human_attribute_name(:time)
            th= model_class.human_attribute_name(:runner_id)
            th= model_class.human_attribute_name(:status_id)
            th= model_class.human_attribute_name(:authkey_id)
            th= model_class.human_attribute_name(:wish)
            th= model_class.human_attribute_name(:created_at)
            th=t '.actions', :default => t("helpers.actions")
        tbody
          - @anys.each do |baton|
            tr
              td= link_to baton.id, baton_path(baton)
              td= baton.taskname
              td= baton.phone
              td= baton.detail
              td= baton.address
              td= baton.date
              td= baton.time
              td
                - if baton.runner_id.eql?(1)
                  | 다니엘
                - elsif baton.runner_id.eql?(2)
                  | 카사노바
                - elsif baton.runner_id.eql?(3)
                  | 헐크
                - elsif baton.runner_id.eql?(4)
                  | 팅커벨
                - else
                  | 아무나
              td
                - if baton.status_id.eql?(0)
                  | 등록대기상태
                - elsif baton.status_id.eql?(1)
                  | 진행중
                - elsif baton.status_id.eql?(2)
                  | 완료
              td= baton.authkey.authkey
              td= baton.wish
              td=l baton.created_at
              td
                = link_to t('.edit', :default => t("helpers.links.edit")), edit_baton_path(baton), :class => 'btn btn-mini'

app/views/batons/daniel.html.slim
- model_class = Baton
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize
.tabbable
  ul.nav.nav-tabs
    li.active
      a href="#me" data-toggle="tab" Me
    li
      a href="#anyone" data-toggle="tab" Anyone
  .tab-content
    .tab-pane.active#me
      table class="table table-striped"
        thead
          tr
            th= model_class.human_attribute_name(:id)
            th= model_class.human_attribute_name(:taskname)
            th= model_class.human_attribute_name(:phone)
            th= model_class.human_attribute_name(:detail)
            th= model_class.human_attribute_name(:address)
            th= model_class.human_attribute_name(:date)
            th= model_class.human_attribute_name(:time)
            th= model_class.human_attribute_name(:runner_id)
            th= model_class.human_attribute_name(:status_id)
            th= model_class.human_attribute_name(:authkey_id)
            th= model_class.human_attribute_name(:wish)
            th= model_class.human_attribute_name(:created_at)
            th=t '.actions', :default => t("helpers.actions")
        tbody
          - @batons.each do |baton|
            tr
              td= link_to baton.id, baton_path(baton)
              td= baton.taskname
              td= baton.phone
              td= baton.detail
              td= baton.address
              td= baton.date
              td= baton.time
              td
                - if baton.runner_id.eql?(1)
                  | 다니엘
                - elsif baton.runner_id.eql?(2)
                  | 카사노바
                - elsif baton.runner_id.eql?(3)
                  | 헐크
                - elsif baton.runner_id.eql?(4)
                  | 팅커벨
                - else
                  | 아무나
              td
                - if baton.status_id.eql?(0)
                  | 등록대기상태
                - elsif baton.status_id.eql?(1)
                  | 진행중
                - elsif baton.status_id.eql?(2)
                  | 완료
              td= baton.authkey.authkey
              td= baton.wish
              td=l baton.created_at
              td
                = link_to t('.edit', :default => t("helpers.links.edit")), edit_baton_path(baton), :class => 'btn btn-mini'
    .tab-pane#anyone
      table class="table table-striped"
        thead
          tr
            th= model_class.human_attribute_name(:id)
            th= model_class.human_attribute_name(:taskname)
            th= model_class.human_attribute_name(:phone)
            th= model_class.human_attribute_name(:detail)
            th= model_class.human_attribute_name(:address)
            th= model_class.human_attribute_name(:date)
            th= model_class.human_attribute_name(:time)
            th= model_class.human_attribute_name(:runner_id)
            th= model_class.human_attribute_name(:status_id)
            th= model_class.human_attribute_name(:authkey_id)
            th= model_class.human_attribute_name(:wish)
            th= model_class.human_attribute_name(:created_at)
            th=t '.actions', :default => t("helpers.actions")
        tbody
          - @anys.each do |baton|
            tr
              td= link_to baton.id, baton_path(baton)
              td= baton.taskname
              td= baton.phone
              td= baton.detail
              td= baton.address
              td= baton.date
              td= baton.time
              td
                - if baton.runner_id.eql?(1)
                  | 다니엘
                - elsif baton.runner_id.eql?(2)
                  | 카사노바
                - elsif baton.runner_id.eql?(3)
                  | 헐크
                - elsif baton.runner_id.eql?(4)
                  | 팅커벨
                - else
                  | 아무나
              td
                - if baton.status_id.eql?(0)
                  | 등록대기상태
                - elsif baton.status_id.eql?(1)
                  | 진행중
                - elsif baton.status_id.eql?(2)
                  | 완료
              td= baton.authkey.authkey
              td= baton.wish
              td=l baton.created_at
              td
                = link_to t('.edit', :default => t("helpers.links.edit")), edit_baton_path(baton), :class => 'btn btn-mini'

app/views/batons/edit.html.slim
- model_class = Baton
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/batons/hulk.html.slim
- model_class = Baton
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize
.tabbable
  ul.nav.nav-tabs
    li.active
      a href="#me" data-toggle="tab" Me
    li
      a href="#anyone" data-toggle="tab" Anyone
  .tab-content
    .tab-pane.active#me
      table class="table table-striped"
        thead
          tr
            th= model_class.human_attribute_name(:id)
            th= model_class.human_attribute_name(:taskname)
            th= model_class.human_attribute_name(:phone)
            th= model_class.human_attribute_name(:detail)
            th= model_class.human_attribute_name(:address)
            th= model_class.human_attribute_name(:date)
            th= model_class.human_attribute_name(:time)
            th= model_class.human_attribute_name(:runner_id)
            th= model_class.human_attribute_name(:status_id)
            th= model_class.human_attribute_name(:authkey_id)
            th= model_class.human_attribute_name(:wish)
            th= model_class.human_attribute_name(:created_at)
            th=t '.actions', :default => t("helpers.actions")
        tbody
          - @batons.each do |baton|
            tr
              td= link_to baton.id, baton_path(baton)
              td= baton.taskname
              td= baton.phone
              td= baton.detail
              td= baton.address
              td= baton.date
              td= baton.time
              td
                - if baton.runner_id.eql?(1)
                  | 다니엘
                - elsif baton.runner_id.eql?(2)
                  | 카사노바
                - elsif baton.runner_id.eql?(3)
                  | 헐크
                - elsif baton.runner_id.eql?(4)
                  | 팅커벨
                - else
                  | 아무나
              td
                - if baton.status_id.eql?(0)
                  | 등록대기상태
                - elsif baton.status_id.eql?(1)
                  | 진행중
                - elsif baton.status_id.eql?(2)
                  | 완료
              td= baton.authkey.authkey
              td= baton.wish
              td=l baton.created_at
              td
                = link_to t('.edit', :default => t("helpers.links.edit")), edit_baton_path(baton), :class => 'btn btn-mini'
    .tab-pane#anyone
      table class="table table-striped"
        thead
          tr
            th= model_class.human_attribute_name(:id)
            th= model_class.human_attribute_name(:taskname)
            th= model_class.human_attribute_name(:phone)
            th= model_class.human_attribute_name(:detail)
            th= model_class.human_attribute_name(:address)
            th= model_class.human_attribute_name(:date)
            th= model_class.human_attribute_name(:time)
            th= model_class.human_attribute_name(:runner_id)
            th= model_class.human_attribute_name(:status_id)
            th= model_class.human_attribute_name(:authkey_id)
            th= model_class.human_attribute_name(:wish)
            th= model_class.human_attribute_name(:created_at)
            th=t '.actions', :default => t("helpers.actions")
        tbody
          - @anys.each do |baton|
            tr
              td= link_to baton.id, baton_path(baton)
              td= baton.taskname
              td= baton.phone
              td= baton.detail
              td= baton.address
              td= baton.date
              td= baton.time
              td
                - if baton.runner_id.eql?(1)
                  | 다니엘
                - elsif baton.runner_id.eql?(2)
                  | 카사노바
                - elsif baton.runner_id.eql?(3)
                  | 헐크
                - elsif baton.runner_id.eql?(4)
                  | 팅커벨
                - else
                  | 아무나
              td
                - if baton.status_id.eql?(0)
                  | 등록대기상태
                - elsif baton.status_id.eql?(1)
                  | 진행중
                - elsif baton.status_id.eql?(2)
                  | 완료
              td= baton.authkey.authkey
              td= baton.wish
              td=l baton.created_at
              td
                = link_to t('.edit', :default => t("helpers.links.edit")), edit_baton_path(baton), :class => 'btn btn-mini'

app/views/batons/index.html.slim
- model_class = Baton
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:taskname)
      th= model_class.human_attribute_name(:phone)
      th= model_class.human_attribute_name(:detail)
      th= model_class.human_attribute_name(:address)
      th= model_class.human_attribute_name(:date)
      th= model_class.human_attribute_name(:time)
      th= model_class.human_attribute_name(:runner_id)
      th= model_class.human_attribute_name(:status_id)
      th= model_class.human_attribute_name(:authkey_id)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @batons.each do |baton|
      tr
        td= link_to baton.id, baton_path(baton)
        td= baton.taskname
        td= baton.phone
        td= baton.detail
        td= baton.address
        td= baton.date
        td= baton.time
        td
          - if baton.runner_id.eql?(1)
            | 다니엘
          - elsif baton.runner_id.eql?(2)
            | 카사노바
          - elsif baton.runner_id.eql?(3)
            | 헐크
          - elsif baton.runner_id.eql?(4)
            | 팅커벨
          - else
            | 아무나
        td= baton.status_id
        td= baton.authkey.authkey
        td=l baton.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_baton_path(baton), :class => 'btn btn-mini'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), baton_path(baton), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

app/views/batons/new.html.slim
- model_class = Baton
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/batons/show.html.slim
- model_class = Baton
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human

p
  strong= model_class.human_attribute_name(:taskname) + ':'
  br
  = @baton.taskname
p
  strong= model_class.human_attribute_name(:phone) + ':'
  br
  = @baton.phone
p
  strong= model_class.human_attribute_name(:detail) + ':'
  br
  = @baton.detail
p
  strong= model_class.human_attribute_name(:address) + ':'
  br
  = @baton.address
p
  strong= model_class.human_attribute_name(:date) + ':'
  br
  = @baton.date
p
  strong= model_class.human_attribute_name(:time) + ':'
  br
  = @baton.time

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), batons_path, :class => 'btn'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_baton_path(@baton), :class => 'btn'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), baton_path(@baton), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/batons/think.html.slim
- model_class = Baton
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize
.tabbable
  ul.nav.nav-tabs
    li.active
      a href="#me" data-toggle="tab" Me
    li
      a href="#anyone" data-toggle="tab" Anyone
  .tab-content
    .tab-pane.active#me
      table class="table table-striped"
        thead
          tr
            th= model_class.human_attribute_name(:id)
            th= model_class.human_attribute_name(:taskname)
            th= model_class.human_attribute_name(:phone)
            th= model_class.human_attribute_name(:detail)
            th= model_class.human_attribute_name(:address)
            th= model_class.human_attribute_name(:date)
            th= model_class.human_attribute_name(:time)
            th= model_class.human_attribute_name(:runner_id)
            th= model_class.human_attribute_name(:status_id)
            th= model_class.human_attribute_name(:authkey_id)
            th= model_class.human_attribute_name(:wish)
            th= model_class.human_attribute_name(:created_at)
            th=t '.actions', :default => t("helpers.actions")
        tbody
          - @batons.each do |baton|
            tr
              td= link_to baton.id, baton_path(baton)
              td= baton.taskname
              td= baton.phone
              td= baton.detail
              td= baton.address
              td= baton.date
              td= baton.time
              td
                - if baton.runner_id.eql?(1)
                  | 다니엘
                - elsif baton.runner_id.eql?(2)
                  | 카사노바
                - elsif baton.runner_id.eql?(3)
                  | 헐크
                - elsif baton.runner_id.eql?(4)
                  | 팅커벨
                - else
                  | 아무나
              td
                - if baton.status_id.eql?(0)
                  | 등록대기상태
                - elsif baton.status_id.eql?(1)
                  | 진행중
                - elsif baton.status_id.eql?(2)
                  | 완료
              td= baton.authkey.authkey
              td= baton.wish
              td=l baton.created_at
              td
                = link_to t('.edit', :default => t("helpers.links.edit")), edit_baton_path(baton), :class => 'btn btn-mini'
    .tab-pane#anyone
      table class="table table-striped"
        thead
          tr
            th= model_class.human_attribute_name(:id)
            th= model_class.human_attribute_name(:taskname)
            th= model_class.human_attribute_name(:phone)
            th= model_class.human_attribute_name(:detail)
            th= model_class.human_attribute_name(:address)
            th= model_class.human_attribute_name(:date)
            th= model_class.human_attribute_name(:time)
            th= model_class.human_attribute_name(:runner_id)
            th= model_class.human_attribute_name(:status_id)
            th= model_class.human_attribute_name(:authkey_id)
            th= model_class.human_attribute_name(:wish)
            th= model_class.human_attribute_name(:created_at)
            th=t '.actions', :default => t("helpers.actions")
        tbody
          - @anys.each do |baton|
            tr
              td= link_to baton.id, baton_path(baton)
              td= baton.taskname
              td= baton.phone
              td= baton.detail
              td= baton.address
              td= baton.date
              td= baton.time
              td
                - if baton.runner_id.eql?(1)
                  | 다니엘
                - elsif baton.runner_id.eql?(2)
                  | 카사노바
                - elsif baton.runner_id.eql?(3)
                  | 헐크
                - elsif baton.runner_id.eql?(4)
                  | 팅커벨
                - else
                  | 아무나
              td
                - if baton.status_id.eql?(0)
                  | 등록대기상태
                - elsif baton.status_id.eql?(1)
                  | 진행중
                - elsif baton.status_id.eql?(2)
                  | 완료
              td= baton.authkey.authkey
              td= baton.wish
              td=l baton.created_at
              td
                = link_to t('.edit', :default => t("helpers.links.edit")), edit_baton_path(baton), :class => 'btn btn-mini'

app/views/batons/useredit.html.slim
.container
  .con-back
    #runnerinfo
      = image_tag "slide1.png"
    br
    br
  - flash.each do |name, msg|
    div class="alert alert-#{name == :notice ? 'success' : 'error'}"
      a.close data-dismiss="alert" x
      = msg
  = simple_form_for @baton, url:{controller:"batons", action: "update"},:html => { :class => "form-horizontal" } do |f|
    = f.input :taskname, label:"어떤 일을 시키실래요?", disabled: true
    = f.input :phone, label: "전화번호", disabled: true
    = f.input :detail, label: "세부사항", hint: "일을 할때 필요한 모든 상세사항을 적어주세요!"
    = f.input :address, label: "주소", hint: "러너가 일을 수행할 주소를 구체적으로 끝까지 적어주세요!"
    = f.input :date, label: "날짜", as: :string, input_html: {class: 'datepicker'},hint: "1차 이용가능 기간은 9월 24일부터 9월 28일까지입니다!"
    = f.input :time, label: "시간",as: :string, input_html: {class: 'timepickeredit'},hint: "신청 가능시간은 오전 10시(10:00AM)부터 오후 10시(10:00PM)까지입니다!"
    .form-actions#createbtn
      = link_to "뒤로가기", find_path, :class => 'btn'
      '
      = f.button :submit, :class => 'btn-primary'