config/routes.rb
Batontouchme::Application.routes.draw do
  resources :testers, only: [:new, :create, :index]

  resources :batons, only: [:index, :create, :update, :destroy, :edit] do
    collection do
      get 'daniel'
      get 'casa'
      get 'hulk'
      get 'think'
    end

    member do
      get 'useredit'
    end
  end

  resources :keys  
  resources :sessions, only: [:new, :create, :destroy]

  match '/signin', to:'sessions#new'
  match '/signout', to:'sessions#destroy', via: :delete

  match '/home', to: 'main#home'
  match '/info', to: 'main#info'
  match '/runners', to: 'main#runners'
  match '/find', to: 'main#find'
  match '/authkeys', to: 'main#authkeys'

  match '/runners/daniel', to: 'main#daniel'
  match '/runners/casanova', to: 'main#casanova'
  match '/runners/hulk', to: 'main#hulk'
  match '/runners/thinkerbell', to: 'main#thinkerbell'

  match '/runners/daniel/regist1', to: 'main#regist1'
  match '/runners/casanova/regist2', to: 'main#regist2'
  match '/runners/hulk/regist3', to: 'main#regist3'
  match '/runners/thinkerbell/regist4', to: 'main#regist4'

  match '/runners/daniel/create1', to: 'main#create1', via: [:post]
  match '/runners/casanova/create2', to: 'main#create2', via: [:post]
  match '/runners/hulk/create3', to: 'main#create3', via: [:post]
  match '/runners/thinkerbell/create4', to: 'main#create4', via: [:post]

  match '/runners/regist', to: 'main#regist'
  match '/runners/create', to: 'main#create'

  root to: "main#home"

end

app/views/layouts/_footer.html.slim
.background	
	.container
		footer
			center @2012 All rights reserved.
			br
			br
			br

app/views/layouts/_header.html.slim
header.navbar.navbar-static-top
	.navbar-inner
		.container
			.brand
				= link_to image_tag("logo.png", class: "logosize"), root_path
			nav#nav-margin
				ul.nav
					li#tabli 
						= link_to info_path do
							span#tablogo 바톤터치는?
					li#tabli
						= link_to runners_path do
							span#tablogo 바톤 전달하기
					li#tabli
						= link_to new_tester_path do
							span#tablogo 나도 러너 되기!
					li#tabli
						= link_to authkeys_path do
							span#tablogo 인증키 전달하기!
					li#tabli
						= link_to find_path do
							span#tablogo 내 바톤은 어디에?
					

app/views/layouts/application.html.slim
doctype
html
head
	= stylesheet_link_tag    "application", :media => "all"
	= javascript_include_tag "application"
	= csrf_meta_tags
	title BatonTouchMe
body

	= render "layouts/header"
	= yield
	= render "layouts/footer"